version: 0.2

phases:
  pre_build:
    commands:
      - echo Getting CodeArtifact auth token...
      - export CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token --domain webapp-demo --domain-owner 905418286373 --query authorizationToken --output text)
    

  build:
    commands:
      - echo Build started on `date`
      - mvn -s settings.xml package
      - ls -R target
artifacts:
  files:
    - target/webapp-build.war



